version: '3'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    ports:
      - "4001:2379"  # Porta cliente
      - "2380:2380"  # Porta de comunicação entre peers
    environment:
      - ETCD_NAME=etcd-node
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - etcd-data:/etcd-data

volumes:
  etcd-data:
