version: '3'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    command:
      - etcd
      - --name etcd-node
      - --data-dir /etcd-data
      - --listen-client-urls http://0.0.0.0:2379
      - --advertise-client-urls http://etcd:2379
    volumes:
      - etcd-data:/etcd-data

volumes:
  etcd-data:
